### ISSUE TITLE
plot function error

### ISSUE THREAD

**Issue by peuclide** [StuntsPT/Structure_threader#83]
Hi, I am using structure_threader on some microsatellite data and have no problem getting structure to run, but no plots are created AND when I try to plot manually with the plot function I get a similar error. 

__Here is what I submit:__

structure_threader plot -i ./all_sites -f structure -K 2 3 4 -o ./all_sites/plots --pop ./all_sites/popfile

__Here is the trace:__

Traceback (most recent call last):
  File "/home/peuclide/.local/bin/structure_threader", line 11, in <module>
    sys.exit(main())
  File "/home/peuclide/.local/lib/python3.6/site-packages/structure_threader/structure_threader.py", line 336, in main
    plots_only(arg)
  File "/home/peuclide/.local/lib/python3.6/site-packages/structure_threader/structure_threader.py", line 265, in plots_only
    use_ind=arg.use_ind)
  File "/home/peuclide/.local/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 987, in main
    klist = PlotList(result_files, fmt, popfile=popfile, indfile=indfile)
  File "/home/peuclide/.local/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 389, in __init__
    kobj = PlotK(fpath, self.fmt)
  File "/home/peuclide/.local/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 106, in __init__
    parse_methods[self.fmt]()
  File "/home/peuclide/.local/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 257, in _parse_structure
    self._parse_usepopinfo(flh, end_parsing_string)
  File "/home/peuclide/.local/lib/python3.6/site-packages/structure_threader/plotter/structplot.py", line 177, in _parse_usepopinfo
    cl_vals = [vals for k, vals in sorted(qvalues_dic.items())]
TypeError: '<' not supported between instances of 'int' and 'str'

I updated matplotlib which did not help. This very well could be a issue with my syntax but figured I would report to you since I had not been successful getting anything to plot. 

Thanks,

Peter

**Comment by peuclide** [comment]
UPDATE: I was running structure with the pop flag on and did not realize this would prevent plotting. Once the popflag was changed to "0" everything worked fine.
