### ISSUE TITLE
Structure_threader issue

### ISSUE THREAD

**Issue by Ram-Nagar** [StuntsPT/Structure_threader#84]
Hi Theere, 
I ma trying to run structure_threader with following command:

structure_threader run -K 6 -R 100 -i WGvarients.DP3g95maf05.sorted2.recode.strct_in -o ./str_out/ -t 4 -st /home/ram/tools/structure_kernel_source/structure_kernel_src/structure

It is throwing error:

"Traceback (most recent call last):
  File "/home/ram/miniconda2/envs/python3/bin/structure_threader", line 11, in <module>
    sys.exit(main())
  File "/home/ram/miniconda2/envs/python3/lib/python3.5/site-packages/structure_threader/structure_threader.py", line 332, in main
    full_run(arg)
  File "/home/ram/miniconda2/envs/python3/lib/python3.5/site-packages/structure_threader/structure_threader.py", line 290, in full_run
    bestk = structure_harvester(arg.outpath, wrapped_prog)
  File "/home/ram/miniconda2/envs/python3/lib/python3.5/site-packages/structure_threader/structure_threader.py", line 183, in structure_harvester
    bestk = sh.main(resultsdir, outdir)
  File "/home/ram/miniconda2/envs/python3/lib/python3.5/site-packages/structure_threader/evanno/structureHarvester.py", line 169, in main
    harvestFiles(data, resultsdir)
  File "/home/ram/miniconda2/envs/python3/lib/python3.5/site-packages/structure_threader/evanno/structureHarvester.py", line 87, in harvestFiles
    'the results directory %s' % resultsdir)
structure_threader.evanno.structureHarvester.Exception: Error, unable to locate any _f files in the results directory /home/ram/Pst_WholeGenome_phylogenomics/finalVCF/vcfCleanSamples/pop_genetics/stracture_analysis/str_out"

Could you please have a look at it and let me know what is the issue.
Thanks
Ram

**Comment by StuntsPT** [comment]
Hi Ram,
*Structure_threader* seems to be having trouble finding the STRUCTURE output files (which should be under `/home/ram/Pst_WholeGenome_phylogenomics/finalVCF/vcfCleanSamples/pop_genetics/stracture_analysis/str_out`) in order to run Evanno's test to find the best K.
Can you please post the results of the following command:

```
ls /home/ram/Pst_WholeGenome_phylogenomics/finalVCF/vcfCleanSamples/pop_genetics/stracture_analysis/str_out/
```
If there are any long files in that directory, can you please post the contents of one such file?

Francisco

**Comment by Ram-Nagar** [comment]
Hi Francisco,
I have a look at the log file and what I understand that structure complaining about missing data in the input file. See the log file in the attachment.

I have converted a multisample vcf file into structure format using Plink with the following command.

plink --vcf WGvarients.DP3g95maf05.sorted2.recode.vcf --recode structure --double-id --allow-extra-chr --out WGvarients.DP3g95maf05.sorted2

Is there any better way of converting a multi-sample vcf file to structure format?

Thanks
Ram
________________________________

**Comment by StuntsPT** [comment]
Hi Ram,
I usually resort to [PGDSpider](http://www.cmpg.unibe.ch/software/PGDSpider/) for that sort of conversions. It's actually quite a versatile piece of software.
If you post the first few lines of your input file, the error message and your `mainparams` file I might be able to assist further.

**Comment by Toral-Manvar** [comment]
`structure_threader run -st ./console_structure/console/structure -K 10 -R 10 -i test_structure_input.txt -o ./structure_threader_out -t 60 --params console_structure/console/mainparams`

> ERROR:

```
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep10 -D 2153978 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep9 -D 940261 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep8 -D 8867621 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep7 -D 786598 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep6 -D 3922463 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep2 -D 3995168 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep5 -D 6870574 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep3 -D 3231867 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep10 -D 4070331 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep1 -D 3436064 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep9 -D 9407159 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 10 -i test_structure_input.txt -o ./structure_threader_out/str_K10_rep4 -D 9555008 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep7 -D 8972939 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep8 -D 4197241 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep4 -D 2065414 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep5 -D 5302281 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep3 -D 3373205 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep2 -D 9764801 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep10 -D 8534425 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep1 -D 5274171 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep9 -D 9723141 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep8 -D 2574541 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep6 -D 3506606 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep7 -D 9355543 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 9 -i test_structure_input.txt -o ./structure_threader_out/str_K9_rep6 -D 8526408 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep5 -D 569392 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep3 -D 4796772 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep4 -D 4485235 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep2 -D 902448 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep10 -D 483266 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 8 -i test_structure_input.txt -o ./structure_threader_out/str_K8_rep1 -D 4046535 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep9 -D 87549 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep8 -D 9673387 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep5 -D 6340341 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep6 -D 5531738 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep4 -D 2666975 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep3 -D 4768450 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep1 -D 3931647 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep2 -D 698914 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 7 -i test_structure_input.txt -o ./structure_threader_out/str_K7_rep7 -D 5948592 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep10 -D 638634 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep9 -D 1058594 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep7 -D 2625379 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep8 -D 9800535 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep6 -D 2090562 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep5 -D 9555347 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep3 -D 4822350 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep4 -D 4682381 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep1 -D 6303807 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 6 -i test_structure_input.txt -o ./structure_threader_out/str_K6_rep2 -D 8614837 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep10 -D 9751992 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep5 -D 5892951 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep8 -D 9494016 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep7 -D 2457905 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep9 -D 8031362 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep6 -D 1384335 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep3 -D 8026998 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep4 -D 4045072 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep1 -D 6030994 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 5 -i test_structure_input.txt -o ./structure_threader_out/str_K5_rep2 -D 8562949 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep10 -D 8540660 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep6 -D 6732660 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep5 -D 5822768 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep3 -D 9037371 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep8 -D 3515347 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep4 -D 9573427 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep2 -D 8698501 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep9 -D 1354307 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep7 -D 430609 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 4 -i test_structure_input.txt -o ./structure_threader_out/str_K4_rep1 -D 6397496 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep8 -D 300134 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep7 -D 1903949 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep6 -D 2995045 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep9 -D 3938341 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep5 -D 3353112 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep10 -D 6844774 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep3 -D 9150602 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep2 -D 2088698 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep1 -D 2913854 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 3 -i test_structure_input.txt -o ./structure_threader_out/str_K3_rep4 -D 4900392 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep10 -D 8677474 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep8 -D 7192091 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep9 -D 6215541 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep7 -D 4587218 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep6 -D 5369380 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep5 -D 3797654 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep4 -D 3459332 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep3 -D 1798683 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep2 -D 4987626 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep10 -D 9225301 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep9 -D 7050025 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep8 -D 9567106 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 2 -i test_structure_input.txt -o ./structure_threader_out/str_K2_rep1 -D 5048950 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep7 -D 6252929 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep6 -D 8670248 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep5 -D 7333040 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep4 -D 9051635 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep2 -D 425069 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep1 -D 9671986 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
INFO: Running: ./console_structure/console/structure -K 1 -i test_structure_input.txt -o ./structure_threader_out/str_K1_rep3 -D 535191 -m ./console_structure/console/mainparams -e ./console_structure/console/extraparams
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.5/dist-packages/structure_threader/structure_threader.py", line 103, in runprogram
    stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: './console_structure/console/structure'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/structure_threader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/structure_threader/structure_threader.py", line 349, in main
    full_run(arg)
  File "/usr/local/lib/python3.5/dist-packages/structure_threader/structure_threader.py", line 298, in full_run
    structure_threader(wrapped_prog, arg)
  File "/usr/local/lib/python3.5/dist-packages/structure_threader/structure_threader.py", line 151, in structure_threader
    pool = Pool(arg.threads).map(temp, jobs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: './console_structure/console/structure'
```

```
[test_structure_input.txt](https://github.com/StuntsPT/Structure_threader/files/3930593/test_structure_input.txt)
[extraparams.txt](https://github.com/StuntsPT/Structure_threader/files/3930594/extraparams.txt)
[mainparams.txt](https://github.com/StuntsPT/Structure_threader/files/3930595/mainparams.txt)
```

**Here, PGDSpider was used fro converting VCF file obtained from tassel5 to structure input**
Thank you.

**Comment by StuntsPT** [comment]
Hi @Toral-Manvar .
It seems that *Structure_threader* cannot find the `structure` binary. Are you sure you have a `structure` binary under `./console_structure/console/structure`?
You seem to have installed `*Structure_threader* as root, so you should have a `structure` binary under `/usr/local/bin/structure`. Try replacing `-st ./console_structure/console/structure` with `-st /usr/bin/local/structure` and see if that solves the issue.

**Comment by Toral-Manvar** [comment]
Thanks a ton StuntsPT. This solved my error and saved by day of trouble shooting.  
But, even after running for more than 6 hours there is no file generated in output folder.
Is it normal?
Note: I am working on server with 60 cores and parameters like 5000 burnins and 50000 MCMC for 192 individual and >20K SNPs.

**Comment by StuntsPT** [comment]
That is a huge dataset.
`STRUCTURE` was never meant to be used with this amount of data.
I'd suggest either down-sampling the number of SNPs (maybe try with sets of 3K SNPs), or use a different program for your analysis, such as *fastStructure* or *ALStructure* (you can wrap both from *Structure_threader* for optimal performance and ease of use).

**Comment by Toral-Manvar** [comment]
Can't thank you enough for developing structure_threader. Unlike running for months using structure, my run got over in just 4 days using structure_threader.

**Comment by StuntsPT** [comment]
That's great to hear! =-)
Don't forget to cite our paper, so we can keep on applying for funding for maintaining *Structure_threader* and developing new programs!
I'll close the issue now, since it was opened almost 6 months ago.
