### ISSUE TITLE
Error running faststructure

### ISSUE THREAD

**Issue by royfrancis** [StuntsPT/Structure_threader#87]
Hi,
I am running faststructure like this.

```
~/.local/bin/structure_threader run --no_tests=True --no_plots=True --ind ind.txt -Klist 2 -R 5 -i ../sb.bed -o structure_threader -t 10 -fs ~/programs/fastStructure/structure.py

INFO: Running: python2 /home/roy/programs/fastStructure/structure.py -K 4 --input /sb --output /structure_threader/fS_run_K --format bed --seed 1235813
INFO: Writing logfile for K2, replicate 1. Please wait...

CRITICAL: 1 faststructure runs exited with errors. Check the log files of the following output files:
ERROR: /structure_threader/fS_run_K
```

Inside the log file, I have :

```
Traceback (most recent call last):
  File "/home/roy/programs/fastStructure/structure.py", line 3, in <module>
    import fastStructure 
  File "__init__.pxd", line 885, in init fastStructure
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```
Any idea what this error might be?

My exploration to resolve this ...

I tried to run faststructure directly like this:

```
python ~/programs/fastStructure/structure.py -K 2 --input=../sb --output="temp" --full

  File "/home/roy/programs/fastStructure/structure.py", line 44
    print "%s prior is not currently implemented, defaulting to the simple prior"
                                                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("%s prior is not currently implemented, defaulting to the simple prior")?
```

This error is because its python 3. If I run the above in python 2, it works fine. That makes sense because faststructure is to be run in python 2.

So I don't know how all this works. structure_threader running in python 3 which requires faststructure to be run in python 2. And I don't know if this has anything to do with the first error.

**Comment by StuntsPT** [comment]
Hi @royfrancis, 
Sine in your system `python` points to `python3` I'm assuming it is "Arch Linux" based.
I will try to reproduce your issue in a similar environment.
However, in the meantime, you can try to work around it by pointing *Strucutre_threader* to the bundled binary of `fastStructure`. It should be under `~/.local/bin/fastStructure`.
This binary has it's own bundled `numpy` and should not run into the issue you are seeing.

Furthermore, please try to run `faststructure` like this:

```
python2 ~/programs/fastStructure/structure.py -K 2 --input=../sb --output="temp" --full
```

Francisco

**Comment by royfrancis** [comment]
It's not arch. I am running Ubuntu 18.04. Your suggestion to use the bundled fastStructure worked. Now I run

`~/.local/bin/structure_threader run --no_tests=True --no_plots=True --ind ind.txt -Klist 2 -i ../sb.bed -o structure_threader -t 10 -fs ~/.local/bin/fastStructure`

and it works. Thanks for your quick reply!

**Comment by royfrancis** [comment]
A quick question about replicates. If `-R` cannot be used with fastStructure, how do you suggest we do replicates? Run in a loop with different seed?

**Comment by StuntsPT** [comment]
Good to hear it's working!
As far as I am aware, fastStructure does not support repliacates in it's core. That being said, your solution seems quite reasonable. Don't forget to change the `-o` switch in every loop iteration so you don't overwrite your previous results.

**Comment by StuntsPT** [comment]
I can't reproduce you issue on a machine with Ubuntu 18.04. Are you using `conda`, by chance?

**Comment by royfrancis** [comment]
Yes. I am using conda environment. I had to since fastStructure wanted 2.7 and I had python 3.

**Comment by royfrancis** [comment]
Now I am exporting to different folder for every loop. It would've been nice if I could specify the output filename. ie; change `rep1` to something else. Or even better if it automatically just did what I described above when `-R` is larger than 1. But this is a minor comment. Thanks again.

**Comment by StuntsPT** [comment]
Ok, that could be the reason it's not working.
Can you please post the contents of `conda list --explicit`? This will enable me to replicate your environment.
Regarding the loop - this is the first time I hear about using replicates for fastStructure. I'll keep that in mind and if I get more requests for that feature I'll consider implementing it. =-)
Thank you for your suggestion anyway!

**Comment by royfrancis** [comment]
I have different environments for fastStructure and Structure_threader.

This is for Structure_threader using py3. This is where I got the error.

```
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2019.11.28-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.33.1-h53a641e_8.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-9.2.0-hdf63c60_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgomp-9.2.0-h24d8f2e_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-0_gnu.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-9.2.0-h24d8f2e_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-he1b5a44_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.1-hf484d3e_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1d-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xz-5.2.4-h14c3975_1001.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-8.0-hf8c457e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.10-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.30.1-hcee41ef_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-3.7.6-h357f687_4_cpython.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python_abi-3.7-1_cp37m.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2019.11.28-py37hc8dfbb8_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-46.0.0-py37hc8dfbb8_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.34.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-20.0.2-py_2.tar.bz2
```

This is for faststructure running py2

```
https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2019.11.28-hecc5488_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgfortran-ng-7.3.0-hdf63c60_5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libstdcxx-ng-9.2.0-hdf63c60_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/llvm-openmp-9.0.1-hc9558a2_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/_openmp_mutex-4.5-1_llvm.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libgcc-ng-9.2.0-h24d8f2e_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-he1b5a44_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libopenblas-0.3.8-h5ec1e0e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ncurses-6.1-hf484d3e_1002.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openssl-1.1.1d-h516909a_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zlib-1.2.11-h516909a_1006.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libblas-3.8.0-15_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/readline-8.0-hf8c457e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.6.10-hed695b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libcblas-3.8.0-15_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/liblapack-3.8.0-15_openblas.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.30.1-hcee41ef_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gsl-2.6-h294904e_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-2.7.15-h5a48372_1009.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2019.11.28-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cython-0.29.15-py27he1b5a44_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numpy-1.16.5-py27h95a1406_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scipy-1.2.1-py27h921218d_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-44.0.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.34.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pip-20.0.2-py_2.tar.bz2
```

**Comment by StuntsPT** [comment]
So, I can't install *Structure_threader* using your py2 environment.
Did you install it using the py3 environment, and then switched to the py2 environment to install fastStructure?
That could explain the numpy error (due to version mismatch).

**Comment by royfrancis** [comment]
Yea. my environment setup is weird! :-D
